PREFIX = /usr/local
LIBDIR = $(PREFIX)/lib
VERSION = $(shell sed -n -e 's,^.*[[:blank:]]\+LIVEMEDIA_LIBRARY_VERSION_STRING[[:blank:]]\+"\(.*\)",\1,p' liveMedia/include/liveMedia_version.hh)
##### Change the following for your environment:
